apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      serviceAccountName: {{ include "selenium-dynamic-grid.serviceAccountName" . }}
      containers:
        - name: grid
          image: "{{ .Values.grid.image.repository }}:{{ .Values.grid.image.tag }}"
          imagePullPolicy: {{ .Values.grid.image.pullPolicy }}
          env:
            - name: SE_OPTS
              value: --enable-managed-downloads true
          ports:
            - containerPort: 4444
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /readyz
              port: 4444
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4444
          resources:
            {{- toYaml .Values.grid.resources | nindent 12 }}
          volumeMounts:
            - name: grid-config
              mountPath: /opt/bin/config.toml
              subPath: config.toml
            - name: videos
              mountPath: /videos
        - name: proxy
          image: "openresty/openresty:alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: videos
              mountPath: /videos
      volumes:
        - name: grid-config
          configMap:
            name: grid
        - name: proxy-config
          configMap:
            name: proxy
        - name: videos
          emptyDir: {}
