apiVersion: v1
kind: ConfigMap
metadata:
  name: grid
data:
  config.toml: |
    [node]
    implementation = "com.github.old_horizon.selenium.grid.node.KubernetesNode"

    [kubernetes]
    configs = [
        "selenium/standalone-firefox:{{ .Chart.AppVersion }}", '{"browserName": "firefox"}',
        "selenium/standalone-chrome:{{ .Chart.AppVersion }}", '{"browserName": "chrome"}',
        "selenium/standalone-edge:{{ .Chart.AppVersion }}", '{"browserName": "MicrosoftEdge"}'
    ]
    video-image = "{{ .Values.worker.videoImage.repository }}:{{ .Values.worker.videoImage.tag }}"
    video-image-pull-policy = "{{ .Values.worker.videoImage.pullPolicy }}"
    videos-path = "/videos"
    max-sessions = {{ .Values.config.maxSessions }}
    {{- if .Values.worker.startupTimeout }}
    worker-startup-timeout = {{ .Values.worker.startupTimeout }}
    {{- end }}
    {{- if .Values.worker.image.pullPolicy }}
    worker-image-pull-policy = "{{ .Values.worker.image.pullPolicy }}"
    {{- end }}
    {{- if .Values.worker.resources.requests.cpu }}
    worker-cpu-request = "{{ .Values.worker.resources.requests.cpu }}"
    {{- end }}
    {{- if .Values.worker.resources.requests.memory }}
    worker-memory-request = "{{ .Values.worker.resources.requests.memory }}"
    {{- end }}
    {{- if .Values.worker.resources.limits.cpu }}
    worker-cpu-limit = "{{ .Values.worker.resources.limits.cpu }}"
    {{- end }}
    {{- if .Values.worker.resources.limits.memory }}
    worker-memory-limit = "{{ .Values.worker.resources.limits.memory }}"
    {{- end }}
