apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        location /videos/ {
            alias /videos/;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }

        location / {
            proxy_pass http://localhost:4444;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
