apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        location /videos/ {
            alias /videos/;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }

        location ~ ^/session/.*/se/cdp {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://localhost:5555;
        }

        location ~ ^/session/.*/se/vnc {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://localhost:5555;
        }

        location = /wd/hub/session {
            access_by_lua_block {
                ngx.req.read_body()
                local cjson = require 'cjson'
                local res = cjson.decode(ngx.location.capture('/_hub/wd/hub/session', { method = ngx.HTTP_POST, always_forward_body = true }).body)
                if res['value']['capabilities']['se:cdp'] then
                    local path, r, err = ngx.re.sub(res['value']['capabilities']['se:cdp'], "^ws:\\/\\/.[^\\/]+(.+)$", "$1")
                    res['value']['capabilities']['se:cdp'] = 'ws://' .. ngx.var.http_host .. path
                end
                ngx.say(cjson.encode(res))
            }
        }

        location /_hub {
            internal;
            rewrite ^/[^/]*/(.*) /$1 break;
            proxy_pass http://localhost:4444;
        }

        location / {
            proxy_http_version 1.1;
            proxy_pass http://localhost:4444;
        }
    }
