apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "selenium-dynamic-grid.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
