apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "selenium-dynamic-grid.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "selenium-dynamic-grid.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "selenium-dynamic-grid.serviceAccountName" . }}
