apiVersion: v1
kind: Service
metadata:
  name: selenium
spec:
  selector:
    app: selenium
  ports:
    - name: proxy-port
      protocol: TCP
      port: 80
      targetPort: 80
  type: "{{ .Values.hub.service.type }}"
  {{- if eq .Values.hub.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.hub.service.sourceRanges }}
  {{- end }}
