hub:
  image:
    repository: oldhorizon/selenium/dynamic-grid-hub
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    sourceRanges: []
  resources: {}

node:
  image:
    repository: oldhorizon/selenium/dynamic-grid-node
    pullPolicy: IfNotPresent
    tag: "latest"
  resources: {}

worker:
  startupTimeout: 120
  image:
    pullPolicy: IfNotPresent
  videoImage:
    repository: selenium/video
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    requests: {}
    limits: {}

serviceAccount:
  name: ""

config:
  maxSessions: 2
