apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: selenium-dynamic-grid
build:
  artifacts:
    - image: oldhorizon/selenium/dynamic-grid-hub
      context: ../..
      docker:
        dockerfile: ../docker/hub/Dockerfile
    - image: oldhorizon/selenium/dynamic-grid-node
      context: ../..
      docker:
        dockerfile: ../docker/node/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: dynamic-grid-node
        chartPath: ../helm
        artifactOverrides:
          hub:
            image: oldhorizon/selenium/dynamic-grid-hub
          node:
            image: oldhorizon/selenium/dynamic-grid-node
        imageStrategy:
          helm: {}
