apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: selenium-dynamic-grid
build:
  artifacts:
    - image: oldhorizon/selenium/dynamic-grid
      context: ../..
      docker:
        dockerfile: ../docker/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: selenium-dynamic-grid
        chartPath: ../helm
        setValueTemplates:
          grid.image.repository: '{{.IMAGE_REPO_oldhorizon_selenium_dynamic_grid}}'
          grid.image.tag: '{{.IMAGE_TAG_oldhorizon_selenium_dynamic_grid}}'
