name: pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: build
        run: mvn package
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            target/*.jar
          retention-days: 1
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-e2e-${{ hashFiles('e2e/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-e2e-
      - name: create kubernetes cluster
        uses: helm/kind-action@v1.2.0
      - name: create namespace
        run: kubectl create ns selenium
      - name: setup helm
        uses: azure/setup-helm@v1
        with:
          version: 3.12.0
      - name: setup skaffold and deploy
        uses: hiberbee/github-action-skaffold@1.12.0
        with:
          skaffold-version: 2.8.0
          working-directory: kubernetes/skaffold
          command: run
          namespace: selenium
      - name: setup gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-plugins: screenshot, html-report, xml-report, java
      - name: execute e2e
        run: mvn -f e2e test
      - name: generate report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: e2e report
          path: e2e/reports/xml-report/result.xml
          reporter: java-junit
  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - e2e
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.jar
